env:
- npmdeployusername=$$npmdeployusername
- npmdeploypassword=$$npmdeploypassword
- email=$$email
image: node0.10
publish:
  npm:
    email: $$email
    password: $$npmdeploypassword
    username: $$npmdeployusername
    when:
      branch: master
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
script:
- npm config set ca ""
- npm install
- npm test
